Colour change on Title, Border, and Github logo during Dim/Dark Mode
grey-software/Twitter-Focus pull request #20
Opened 2020-09-09 03:23 UTC by daveavi

Just made a small update to Grey Software Card, so that the title, border, and GitHub logo looks brighter in dim/dark mode.

2020-09-09 16:23 UTC, ArsalaBangash requested changes
My initial idea was having the color #CCCCCC as the dark mode replacement color. I would appreciate it if you could take screenshots of both and attach them to the PR.

2020-09-09 16:23 UTC, ArsalaBangash commented on src/focus.js
> +    var greyTitleColour = "#434343"
Let's pull this out into a const variable called COLOR_PRIMARY

2020-09-09 16:23 UTC, ArsalaBangash commented on src/focus.js
> +        var greyTitleColour = "#757575"
Then this would be COLOR_PRIMARY_DARK. 

Essentially, we'd like to limit the number of inline, unnamed string constants in our codebase!

2020-09-09 16:23 UTC, ArsalaBangash commented on src/manifest.json
> +    "web_accessible_resources": ["icon.png", "logo.png", "paypal.png", "github.svg", "github-dim.svg", "linkedin.svg"]
I think github-dark would be a better name. I think twitter has a dim mode but dark is more widely known. What do you think?

2020-09-09 16:53 UTC, daveavi commented on src/manifest.json
> +    "web_accessible_resources": ["icon.png", "logo.png", "paypal.png", "github.svg", "github-dim.svg", "linkedin.svg"]
I think I agree, i guess maybe I can name it github-dim-dark? Just because it applies to both modes

2020-09-09 17:06 UTC, daveavi commented on src/focus.js
> +    var greyTitleColour = "#434343"
Shouldn't it be a var variable still because we are using this variable to set the colour in the style of the HTML code? The colour of the grey title changes depending on the mode, that's why I didn't change it into a constant.

2020-09-11 14:43 UTC, ArsalaBangash commented on src/focus.js
> +    var greyTitleColour = "#434343"
It should still be var because it changes. I was encouraging that we do 

```
const COLOR_PRIMARY = "#757575"
const COLOR_PRIMARY_DIM_DARK = "#CCCCCC"


....
...
...

var greyTitleColour = COLOR_PRIMARY

if (....)
greyTitleColour = COLOR_PRIMARY_DIM_DARK
```

We could declare these constants on top with all other string colors. At the moment, let's just move these two, and we'll hgve time for more during a greater refactor.

2020-09-11 14:58 UTC, daveavi commented on src/focus.js
> +    var greyTitleColour = "#434343"
this makes sense, I will make the changes now. Thanks for letting me know!

2020-09-12 08:57 UTC, ArsalaBangash approved these changes
Excellent work :D

2020-09-12 08:57 UTC, merged